name: Transfer Code to Server via SSH

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh # Ensure the .ssh directory exists
          echo "${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Validate SSH Key Secret
        run: |
          if [ -z "${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}" ]; then
            echo "Error: HOSTINGER_SSH_PRIVATE_KEY secret is not set or empty."
            exit 1
          fi

      - name: Add host key to known_hosts
        run: ssh-keyscan -H ${{ secrets.HOSTINGER_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_SSH_HOST }} "echo 'Connection test successful'"

      - name: Check destination directory permissions
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_SSH_HOST }} '
            mkdir -p /var/www/hps
            chmod 755 /var/www/hps
          '

      - name: Deploy with rsync
        run: |
          rsync -avvz --progress -e "ssh -o StrictHostKeyChecking=no" \
            --exclude '.git*' \
            --exclude 'node_modules' \
            --exclude 'test' \
            --exclude '.env' \
            --exclude 'logs' \
            ./ ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_SSH_HOST }}:/var/www/hps/

      - name: Verify files
        if: success()
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_SSH_HOST }} '
            ls -la /var/www/hps/
          '
