name: Transfer Code to Server

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

# No special permissions needed for just code transfer
# permissions: ... (removed)

jobs:
  transfer_code: # Renamed from 'deploy'
    name: Transfer Code to Hostinger VPS
    runs-on: ubuntu-latest
    # Removed needs: [build_and_push, test, lint]
    if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate syncing if needed, though not strictly necessary for basic rsync

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}

      - name: Add host key to known_hosts
        run: ssh-keyscan -H ${{ secrets.HOSTINGER_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure target directory exists on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_SSH_HOST }}
          username: ${{ secrets.HOSTINGER_SSH_USER }}
          key: ${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}
          script: |
            echo "Ensuring directory exists: ${{ secrets.HOSTINGER_APP_PATH }}"
            mkdir -p ${{ secrets.HOSTINGER_APP_PATH }}

      - name: Sync files to server via rsync
        run: |
          echo "Syncing files from $(pwd) to ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_SSH_HOST }}:${{ secrets.HOSTINGER_APP_PATH }}/"
          rsync -avzr --delete --exclude='.git/' --exclude='.github/' --exclude='node_modules/' -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.HOSTINGER_SSH_PORT || 22 }}" ./ ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_SSH_HOST }}:${{ secrets.HOSTINGER_APP_PATH }}/
          echo "Sync complete."

      # Removed artifact download, deploy script, compose copy, and rollback steps
